### ISSUE TITLE
Players falling off floating blocks and clipping through small blocks when using /sit

### ISSUE THREAD

**Issue by SecretlyJealous** [SpraxDev/BetterChairs#104]
* **Server Version**:  git-Tuinity-25 (MC: 1.17.1)
* **Plugin Version**:  1.4.0-ALPHA

**Describe the bug**
When using /sit on a block that is floating above ground, pressing shift to unseat yourself will cause you to fall off. We have some players using /sit for their minigame maps but the issue is that when they unsit they basically fall to their death. Is it possible to make it so that unseating yourself will place you above the block you were sitting on?

Another issue is using /sit on small blocks such as head blocks or iron bars for example, when using shift to unseat yourself you end up clipping through the block and into the ground. Is it possible to place the player above the block?

**To Reproduce**
Steps to reproduce the behaviour:
1. Place a block floating above the ground
2. Use /sit
3. Press shift to unseat yourself

**Screenshots, Videos, Logs or Errors**
/sit
![2021-07-29_16 08 28](https://user-images.githubusercontent.com/10485646/127517136-8753fbed-7b06-4bd4-8986-068aeae58ab5.png)

Press shift
![2021-07-29_16 08 32](https://user-images.githubusercontent.com/10485646/127517149-7a615ecc-3ce2-40b5-8847-d68a0bf5664a.png)

**Additional context**
Config: 
```
# BetterChairs Remastered
# 
# Support: https://Sprax.me/Discord
# Updates and Information:
# Statistics: https://bstats.org/plugin/bukkit/BetterChairs%20Remastered/8214
# Information for developers: https://github.com/SpraxDev/BetterChairs/wiki


# You shouldn't make any changes to this
version: 2
Chairs:

  # Allowed distance a player is allowed to have when trying to sit? (-1 to ignore)
  AllowedDistanceToChair: 3

  # Should a player automatically look forward when starting to sit
  AutoRotatePlayer: true

  # Does a player need his hands empty when trying to sit?
  NeedEmptyHands: true

  # Does a chair need signs on both sides attached to be detected as an chair
  NeedsSignsOnBothSides: false

  # Enable this if you want players to be able to sit on chairs
  # while other plugins (like WorldGuard or PlotSquared) are not
  # allowing interactions/use with the chair blocks.
  IgnoreOtherPluginsPreventingInteract: true

  # Enable this if you want BetterChairs to remember a player who used /bc <toggle|on|off> after a plugin reload or him rejoining
  RememberIfPlayerDisabledChairsAfterRelogin: false
  Position:

    # Set to false, if you do not care about a player suffocating while sitting
    NeedAirAbove: true

    # Set to false, to force chairs to have a block below them
    AllowAirBelow: true

  # Can stairs be chairs?
  UseStairs: true

  # Can half slabs be chairs too?
  UseSlabs: true
  LeavingChair:

    # Should a player be teleported to its original position when leaving a chair
    TeleportPlayerToOldLocation: false

    # Should a player keep his head rotation when teleported to its original position
    KeepHeadRotation: true
  Messages:

    # Should the player receive a message when the chair is already occupied
    AlreadyOccupied: false

    # Should the player receive a message when a chair is missing signs on both sided
    NeedsSignsOnBothSides: false

    # Should the player receive a message when he starts sitting
    NowSitting: false
  Regeneration:

    # Should player receive regeneration effect when sitting? (Needs permission BetterChairs.regeneration)
    Enabled: false

    # What amplifier should be applied?
    Amplifier: 1
Filter:
  Worlds:

    # Should we only enable chairs in specific worlds?
    Enabled: false

    # Should be the list below be used as blacklist or whitelist?
    UseAsBlacklist: false

    # List of all enabled/disabled worlds
    Names:
    - worldname
    - worldname2
  Blocks:

    # Should we only enable specific blocks as chairs?
    Enabled: false

    # Setting this to true, won't check if a chair
    # is a stair or slab but only look if it is in the list below
    # 
    # This is kinda experimental.
    # Enabling overwrites 'UseStairs' and 'UseSlabs' further above
    AllowAllTypes: false

    # Should be the list below be used as blacklist or whitelist?
    UseAsBlacklist: false

    # List of all enabled/disabled block types
    # 
    # The names from Minecraft do not always work
    # Full list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    Names:
    - blockname
    - blockname2
Updater:

  # Should we check for new versions and report to the console? (Recommended)
  CheckForUpdates: true

  # Should be notify admins when they join the server? (Permission: BetterChairs.updater)
  NotifyOnJoin: true
```
