### ISSUE TITLE
Prevent interactions with chairs from placing blocks when using PlotSquared

### ISSUE THREAD

**Issue by SecretlyJealous** [SpraxDev/BetterChairs#53]
**Is your feature request related to a problem? Please describe.**
When using PlotSquared in order to sit on chairs you need to enable a flag within plotsquared known as the "use" flag. This flag allows you to define a list of materials players should be able to interact with in the plot even when they aren't added to the plot. If you don't specify oak_stairs for example then players will not be able to right click to sit on the chair which is why you have to specify use: oak_stairs within the plotsquared worlds config. This allows players to sit on chairs without needing to be added to a plot which is great for roleplays such as a classroom for example but the issue is that players can hold a water bucket in their hand for example and right click on the chair while holding the water bucket which will cause the water to be placed on the stair even though they don't have permission to build on that plot. This is not an issue when using full blocks, I've managed to trigger this issue with water and armorstand and I'm guessing it has something to do with the playerinteractevent.

Here's an example of me right clicking to sit on a chair while holding a water bucket even though I don't have permission to place blocks in this plot.
![2020-10-09_23 05 38](https://user-images.githubusercontent.com/10485646/95636044-06bee000-0a86-11eb-84bf-64d23184172c.png)

**Describe the solution you'd like**
Interacting with a chair while holding a block such as an armorstand for example should not trigger block placement.

I really hope there's an easy way of implementing this since players are able to place armorstands or water for example in plots they don't have permission for because they right clicked on a chair while holding that block.

This is my config:
```
version: 1
Chairs:
  AllowedDistanceToChair: 2
  AutoRotatePlayer: true
  NeedEmptyHands: true
  NeedsSignsOnBothSides: false
  UseSlabs: false
  Messages:
    AlreadyOccupied: false
    NeedsSignsOnBothSides: false
    NowSitting: false
  Regeneration:
    Enabled: false
    Amplifier: 1
  UseStairs: true
  LeavingChair:
    TeleportPlayerToOldLocation: true
    KeepHeadRotation: true
Filter:
  Worlds:
    Names:
    - example1
    - example2
    Enabled: false
    UseAsBlacklist: true
Updater:
  CheckForUpdates: false
  NotifyOnJoin: false
```
